// src/components/react/forms/InputWrapper.tsx
import React from 'react';
import Tooltip from './Tooltip';

interface InputWrapperProps {
	id: string;
	label: string;
	prefix?: string;
	tooltip?: string;
	description?: string;
	descClass?: string;
	children?: React.ReactNode;
	input?: React.ReactNode;
	unit?: React.ReactNode;
}

const InputWrapper: React.FC<InputWrapperProps> = ({
	id,
	label,
	prefix = '',
	tooltip = '',
	description = '',
	descClass = 'text-muted',
	children,
	input,
	unit,
}) => {
	return (
		<div className="mb-3">
			{label && (
				<label
					htmlFor={id}
					className="form-label"
					dangerouslySetInnerHTML={{ __html: label }}
				/>
			)}
			{tooltip && <Tooltip tooltip={tooltip} />}
			<div className="input-group">
				{prefix && (
					<span
						className="input-group-text bg-dark text-white"
						dangerouslySetInnerHTML={{ __html: prefix }}
					/>
				)}
				{input}
				{unit}
				{children}
			</div>
			{description && (
				<p className="description">
					<small
						className={descClass}
						dangerouslySetInnerHTML={{ __html: description }}
					/>
				</p>
			)}
		</div>
	);
};

export default InputWrapper;

// CSS can be moved to a separate file or styled-components
const styles = `
.calc-form .input-group input {
  width: auto;
  flex: 2;
}

.calc-form .input-group input + select,
.calc-form .input-group input + span {
  flex: 1;
}
`;

// src/components/vue/forms/v2/InputWrapper.vue
<template>
    <div class="mb-3">
        <label v-if="label" :for="id" class="form-label" v-html="label"></label>
        <Tooltip v-if="tooltip" :tooltip="tooltip" />
        <div class="input-group">
            <span
                v-if="prefix"
                class="input-group-text bg-dark text-white"
                v-html="prefix"
            ></span>
            <slot name="input"></slot>
            <slot name="unit"></slot>
        </div>
        <p v-if="description" class="description">
            <small
                :class="descClass ? descClass : 'text-muted'"
                v-html="description"
            ></small>
        </p>
    </div>
</template>

<script setup lang="ts">
import Tooltip from '../Tooltip.vue';

defineProps<{
    id: string;
    label: string;
    prefix?: string;
    tooltip?: string;
    description?: string;
    descClass?: string;
}>();
</script>

<style>
.calc-form .input-group input {
    width: auto;
    flex: 2;
}

.calc-form .input-group input + select,
.calc-form .input-group input + span {
    flex: 1;
}
</style>
