// src/components/react/forms/ResultTable.tsx
import React from 'react';

interface ResultTableProps {
	children?: React.ReactNode;
	title?: React.ReactNode;
}

const ResultTable: React.FC<ResultTableProps> = ({ children, title }) => {
	return (
		<>
			<style>{`
				#resultsTable tbody tr:last-child td,
				#resultsTable tbody tr:last-child th {
					border-bottom: 0;
				}
			`}</style>
			<div id="resultsTable" className="p-2 rounded border mb-5">
				{title}
				<table className="table mb-0 ">
					<tbody className="align-middle">{children}</tbody>
				</table>
			</div>
		</>
	);
};

export default ResultTable;

// src/components/vue/forms/v2/ResultTable.vue
<template>
	<div id="resultsTable" class="p-2 rounded border mb-5">
		<slot name="title"></slot>
		<table class="table mb-0">
			<tbody class="align-middle">
				<slot></slot>
			</tbody>
		</table>
	</div>
</template>
<style>
#resultsTable tbody tr:last-child td,
#resultsTable tbody tr:last-child th {
	border-bottom: 0;
}
</style>
