// src/components/react/forms/NumberInput.tsx
import React, { useRef, useEffect } from 'react';
import { clampNumber } from '../../vue/utils';

interface NumberInputProps {
	id: string;
	value: number;
	min?: number;
	max?: number;
	step?: number;
	onChange: (value: number) => void;
	[key: string]: any; // For additional HTML attributes
}

const NumberInput: React.FC<NumberInputProps> = ({
	id,
	value,
	min,
	max,
	step,
	onChange,
	...attrs
}) => {
	const inputRef = useRef<HTMLInputElement>(null);

	const updateValue = (event: React.ChangeEvent<HTMLInputElement>) => {
		const newValue = parseFloat(event.target.value);
		const clampedValue = clampNumber(
			newValue,
			min ?? -Infinity,
			max ?? Infinity,
		);

		// Update the input value if it's different from the clamped value
		if (
			inputRef.current &&
			inputRef.current.value !== String(clampedValue)
		) {
			inputRef.current.value = String(clampedValue);
		}

		onChange(clampedValue);
	};

	// Update the input value when the controlled value changes
	useEffect(() => {
		if (inputRef.current && inputRef.current.value !== String(value)) {
			inputRef.current.value = String(value);
		}
	}, [value]);

	return (
		<input
			ref={inputRef}
			id={id}
			type="number"
			className="form-control"
			value={value}
			min={min}
			max={max}
			step={step}
			onChange={updateValue}
			{...attrs}
		/>
	);
};

export default NumberInput;

// src/components/vue/forms/NumberInput.vue
<template>
  <div class="mb-3">
    <label v-if="label" :for="id" class="form-label" v-html="label"></label>
    <tooltip v-if="tooltip" :tooltip="tooltip" />
    <div class="input-group">
      <span
        v-if="prefix"
        class="input-group-text bg-dark text-white"
        v-html="prefix"
      ></span>
      <input
        ref="numberInput"
        :id="id"
        v-bind="attrs"
        type="number"
        class="form-control"
        :value="internalValue"
        :min="min"
        :max="max"
        :step="step"
        @change="($event) => updateValue($event)"
      />
      <span
        v-if="unit"
        class="input-group-text bg-dark text-white"
        v-html="unit"
      ></span>
    </div>
    <p v-if="description" class="description">
      <small class="text-muted" v-html="description"></small>
    </p>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from "vue";
import { clampNumber } from "../utils";
import Tooltip from "./Tooltip.vue";

const emit = defineEmits(["update:modelValue"]);

const props = defineProps<{
  id: string;
  label: string;
  modelValue: number;
  unit?: string;
  prefix?: string;
  tooltip?: string;
  description?: string;
  min?: number;
  max?: number;
  step?: number;
  attrs?: Record<string, unknown>;
}>();

const internalValue = ref<string>(props.modelValue.toString());
const numberInput = ref(null);

const updateValue = (event: Event) => {
  const target = event.target as HTMLInputElement;
  const value = Number(target.value);

  const clampedValue = clampNumber(
    value,
    props.min ?? -Infinity,
    props.max ?? Infinity
  );

  internalValue.value = clampedValue.toString();

  if (
    numberInput.value &&
    internalValue.value === props.modelValue.toString()
  ) {
    // @ts-ignore
    numberInput.value.value = String(clampedValue);
  }

  emit("update:modelValue", clampedValue);
};

// // Watch prop value change and assign to value 'selected' Ref
// watch(
//   () => props.modelValue,
//   (newValue: number) => {
//     internalValue.value = newValue.toString();
//   }
// );
</script>
