// src/components/vue/forms/v2/NumberInput.vue
<template>
    <input
        ref="numberInput"
        :id="id"
        v-bind="attrs"
        type="number"
        class="form-control"
        :value="internalValue"
        :min="min"
        :max="max"
        :step="step"
        @change="($event) => updateValue($event)"
    />
</template>

<script setup lang="ts">
// TODO: Update to use the input wrapper
import { computed, onBeforeMount, ref, watch } from 'vue';
import { clampNumber } from '../../utils';

const emit = defineEmits(['update:modelValue']);

const props = defineProps<{
    id: string;
    modelValue: number;
    min?: number;
    max?: number;
    step?: number;
    attrs?: Record<string, unknown>;
}>();

const internalValue = ref<string>(props.modelValue.toString());
const numberInput = ref(null);

onBeforeMount(() => {});

const updateValue = (event: Event) => {
    const target = event.target as HTMLInputElement;
    const value = parseFloat(target.value);

    let clampedValue = clampNumber(
        value,
        props.min ?? -Infinity,
        props.max ?? Infinity,
    );

    internalValue.value = clampedValue.toString();

    if (
        numberInput.value &&
        internalValue.value === props.modelValue.toString()
    ) {
        // @ts-ignore
        numberInput.value.value = String(clampedValue);
    }

    emit('update:modelValue', clampedValue);
};
</script>

// src/components/react/forms/NumberInput.tsx
import React, { useRef, useEffect } from 'react';
import { clampNumber } from '../../vue/utils';

interface NumberInputProps {
	id: string;
	value: number;
	min?: number;
	max?: number;
	step?: number;
	onChange: (value: number) => void;
	[key: string]: any; // For additional HTML attributes
}

const NumberInput: React.FC<NumberInputProps> = ({
	id,
	value,
	min,
	max,
	step,
	onChange,
	...attrs
}) => {
	const inputRef = useRef<HTMLInputElement>(null);

	const updateValue = (event: React.ChangeEvent<HTMLInputElement>) => {
		const newValue = parseFloat(event.target.value);
		const clampedValue = clampNumber(
			newValue,
			min ?? -Infinity,
			max ?? Infinity,
		);

		// Update the input value if it's different from the clamped value
		if (
			inputRef.current &&
			inputRef.current.value !== String(clampedValue)
		) {
			inputRef.current.value = String(clampedValue);
		}

		onChange(clampedValue);
	};

	// Update the input value when the controlled value changes
	useEffect(() => {
		if (inputRef.current && inputRef.current.value !== String(value)) {
			inputRef.current.value = String(value);
		}
	}, [value]);

	return (
		<input
			ref={inputRef}
			id={id}
			type="number"
			className="form-control"
			value={value}
			min={min}
			max={max}
			step={step}
			onChange={updateValue}
			{...attrs}
		/>
	);
};

export default NumberInput;
