// src/components/vue/forms/v2/UnitSelect.vue
<template>
    <select
        class="form-select bg-dark text-white"
        :value="props.modelValue.label"
        @change="($event) => updateValue($event)"
    >
        <option
            v-for="unitOption in units"
            :value="unitOption.label"
            :selected="unitOption.label === props.modelValue.label"
            v-html="unitOption.label"
        ></option>
    </select>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue';
import type { NumberUnits } from '../types';

const emit = defineEmits(['update:modelValue']);

const props = defineProps<{
    id: string;
    modelValue: NumberUnits;
    units: NumberUnits[];
}>();

const updateValue = (event: Event) => {
    const target = event.target as HTMLInputElement;
    const value = target.value as string;

    const newUnit =
        props.units.find((unit) => unit.label === value) ?? props.units[0];

    console.log('UnitSelect: updateValue', newUnit);

    emit('update:modelValue', newUnit);
};
</script>

// src/components/react/forms/UnitSelect.tsx
import React from 'react';

interface NumberUnit {
	label: string;
	[key: string]: any;
}

interface UnitSelectProps {
	id?: string;
	value: NumberUnit;
	units: NumberUnit[];
	onChange: (unit: NumberUnit) => void;
}

const UnitSelect: React.FC<UnitSelectProps> = ({
	id,
	value,
	units,
	onChange,
}) => {
	const handleChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
		const selectedValue = event.target.value;
		const newUnit =
			units.find((unit) => unit.label === selectedValue) ?? units[0];
		onChange(newUnit);
	};

	return (
		<select
			className="form-select bg-dark text-white"
			value={value.label}
			onChange={handleChange}
		>
			{units.map((unitOption) => (
				<option
					key={unitOption.label}
					value={unitOption.label}
					dangerouslySetInnerHTML={{ __html: unitOption.label }}
				/>
			))}
		</select>
	);
};

export default UnitSelect;
